### PR TITLE
Some fixes and improvements

### PR DESCRIPTION
**Pull request by ricpelo**

### CODE REVIEW

**Comment by a-watson** [comment]
¡Gracias! Hablo solo un poquito español pero estoy agradecido por estos cambios.

**Comment by ricpelo** [comment]
You're welcome! Thanks to you. It's a pleasure :).

**Comment by a-watson** [comment]
Kind of a side note, how was my Spanish? I've tried to keep it fresh but it's been a few years since my last Spanish class.

**Comment by ricpelo** [comment]
Oh, your Spanish is wonderful! Congratulations. I'd understand you perfectly ;). Clearly, your Spanish is far better than my English :).

**Pull request merged**
